import type { SkillLevel } from "@/lib/onboarding-types";
import type { NormalizedProfile, RiskLevel } from "@/lib/profile/normalize";
import { SKILL_LEVEL_SCORE } from "@/lib/profile/normalize";

/**
 * What Gemini proposes per candidate opportunity — qualitative/estimated
 * requirements, not a score. The app (this file) turns these into the
 * final, reproducible Solventia Fit Score. Gemini never invents the
 * final percentage (requirement: fit score must be reproducible from the
 * stored profile, not freely generated by the model).
 */
export interface OpportunityFitFactors {
  requiredSkills: { name: string; minLevel: SkillLevel }[];
  startupCapitalINR: number;
  weeklyHoursNeeded: number;
  riskLevel: RiskLevel;
  motivationAlignment: "high" | "medium" | "low";
  requiresLeadership: boolean;
  requiresSales: boolean;
  soloFriendly: boolean;
  relevantExperienceYears: number;
  requiresDigitalAssets: boolean;
  /** False when the opportunity genuinely requires being physically present
   * somewhere specific (a shop, a client's site, a particular city) — true
   * for anything that can be run from wherever the founder already is. */
  locationFlexible: boolean;
}

export interface FitScoreBreakdown {
  skills: number;
  resources: number;
  time: number;
  motivation: number;
  risk: number;
  experience: number;
  context: number;
}

export interface FitScoreResult {
  total: number;
  breakdown: FitScoreBreakdown;
  maxima: FitScoreBreakdown;
}

export const FIT_SCORE_MAXIMA: FitScoreBreakdown = {
  skills: 20,
  resources: 20,
  time: 15,
  motivation: 15,
  risk: 10,
  experience: 10,
  context: 10,
};

const RISK_ORDER: RiskLevel[] = ["cautious", "balanced", "experimental"];

function clamp(n: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, n));
}

function scoreSkills(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.skills;
  if (factors.requiredSkills.length === 0) return Math.round(max * 0.6);

  const ratios = factors.requiredSkills.map((req) => {
    const owned = profile.skills.find(
      (s) => s.name.toLowerCase().trim() === req.name.toLowerCase().trim(),
    );
    if (!owned) return 0;
    const diff = owned.levelScore - SKILL_LEVEL_SCORE[req.minLevel];
    if (diff >= 0) return 1;
    return clamp(1 + diff / 4, 0, 1);
  });

  const avg = ratios.reduce((a, b) => a + b, 0) / ratios.length;
  return Math.round(avg * max);
}

function scoreResources(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.resources;
  const capitalRatio =
    factors.startupCapitalINR <= 0
      ? 1
      : clamp(profile.resources.capitalINR / factors.startupCapitalINR, 0, 1);

  let score = max * capitalRatio;

  if (factors.requiresDigitalAssets) {
    const hasDigitalAssets = profile.resources.assets.some(
      (a) => a === "A laptop / computer" || a === "A smartphone",
    );
    if (!hasDigitalAssets) score -= max * 0.2;
  }

  return Math.round(clamp(score, 0, max));
}

function scoreTime(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.time;
  const ratio =
    factors.weeklyHoursNeeded <= 0
      ? 1
      : clamp(profile.time.weeklyHours / factors.weeklyHoursNeeded, 0, 1);
  return Math.round(max * ratio);
}

function scoreMotivation(factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.motivation;
  const multiplier = { high: 1, medium: 0.66, low: 0.33 }[factors.motivationAlignment];
  return Math.round(max * multiplier);
}

function scoreRisk(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.risk; // 8 for risk-level distance + 2 for work-style fit
  let score = 8;
  if (profile.risk.appetite) {
    const distance = Math.abs(
      RISK_ORDER.indexOf(profile.risk.appetite) - RISK_ORDER.indexOf(factors.riskLevel),
    );
    score = distance === 0 ? 8 : distance === 1 ? 5 : 2;
  } else {
    score = 5; // unknown appetite — neutral
  }

  let workStyleBonus = 0;
  if (factors.requiresLeadership) {
    if (profile.workStyle.leadership === "Very comfortable") workStyleBonus += 1;
    else if (profile.workStyle.leadership === "Prefer not to") workStyleBonus -= 1;
  } else {
    workStyleBonus += 0.5;
  }
  if (factors.requiresSales) {
    if (profile.workStyle.salesComfort === "I enjoy it") workStyleBonus += 1;
    else if (profile.workStyle.salesComfort === "It makes me uneasy") workStyleBonus -= 1;
  } else {
    workStyleBonus += 0.5;
  }
  if (!factors.soloFriendly && profile.workStyle.soloOrTeam === "Solo") workStyleBonus -= 0.5;

  return Math.round(clamp(score + clamp(workStyleBonus, -2, 2), 0, max));
}

function scoreExperience(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.experience;
  if (factors.relevantExperienceYears <= 0) return max;
  const ratio = clamp(profile.experienceYears / factors.relevantExperienceYears, 0, 1);
  return Math.round(max * ratio);
}

function scoreContext(profile: NormalizedProfile, factors: OpportunityFitFactors): number {
  const max = FIT_SCORE_MAXIMA.context;
  if (factors.locationFlexible) return max;
  // A genuinely location-bound opportunity is a real mismatch for someone
  // who specifically wants remote work — everyone else (no stated
  // preference, or already open to in-person) isn't penalized for it.
  if (profile.workStyle.location === "Remote") return Math.round(max * 0.2);
  return max;
}

/**
 * Deterministic, human-readable flags for genuine hard-constraint
 * mismatches (item 11) — surfaced as an explicit warning rather than
 * silently dropping the opportunity, since exactly 3 come back per
 * generation and there's no larger pool to backfill from without another
 * Gemini call.
 */
export function getConstraintWarnings(
  profile: NormalizedProfile,
  factors: OpportunityFitFactors,
): string[] {
  const warnings: string[] = [];
  if (profile.resources.capitalINR <= 500 && factors.startupCapitalINR > 5_000) {
    warnings.push(
      `This typically needs about ₹${factors.startupCapitalINR.toLocaleString("en-IN")} to start, but your profile has no capital set aside yet.`,
    );
  }
  if (factors.weeklyHoursNeeded > profile.time.weeklyHours * 2 && profile.time.weeklyHours > 0) {
    warnings.push(
      `This realistically needs ~${factors.weeklyHoursNeeded} hrs/week, well beyond your available ${profile.time.weeklyHours} hrs/week.`,
    );
  }
  if (!factors.locationFlexible && profile.workStyle.location === "Remote") {
    warnings.push("This typically requires being physically present somewhere, not fully remote.");
  }
  return warnings;
}

/**
 * Computes the Solventia Fit Score for one opportunity against one
 * normalized profile. Pure and deterministic — the same inputs always
 * produce the same score, so it can be recomputed/audited at any time.
 */
export function computeFitScore(
  profile: NormalizedProfile,
  factors: OpportunityFitFactors,
): FitScoreResult {
  const breakdown: FitScoreBreakdown = {
    skills: scoreSkills(profile, factors),
    resources: scoreResources(profile, factors),
    time: scoreTime(profile, factors),
    motivation: scoreMotivation(factors),
    risk: scoreRisk(profile, factors),
    experience: scoreExperience(profile, factors),
    context: scoreContext(profile, factors),
  };

  const total = Object.values(breakdown).reduce((a, b) => a + b, 0);

  return { total: clamp(total, 0, 100), breakdown, maxima: FIT_SCORE_MAXIMA };
}
