import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";

import { requireUser } from "@/lib/supabase/server";
import type { Database, Json } from "@/lib/supabase/types";
import type { NormalizedProfile } from "@/lib/profile/normalize";
import { computeFitScore } from "@/lib/profile/scoring";
import { generateOpportunityPackageBatch } from "@/lib/ai/prompts/intelligence-package";
import { generateOpportunityDetail } from "@/lib/ai/prompts/opportunity-detail";
import { generateRoadmapPlan } from "@/lib/ai/prompts/roadmap-generation";
import { researchMarketEvidence } from "@/lib/ai/prompts/market-research";
import { MODEL } from "@/lib/ai/gemini.server";
import {
  createRoadmap,
  activateRoadmap,
  archiveActiveRoadmap,
} from "@/lib/actions/roadmap-persistence.server";
import type {
  OpportunityCandidate,
  OpportunityPackage,
  MarketEvidenceItem,
} from "@/lib/ai/schemas";

const CANDIDATES_PER_BATCH = 3;
const RESEARCH_CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

/** Two different founders can land on near-identical business ideas — the
 * underlying market question ("is there demand for X") doesn't change
 * per-user, so it's cached here across everyone rather than re-run per
 * opportunity. Exact-match on category+title only (no fuzzy matching), so
 * this is a real but modest hit rate — still strictly better than never
 * reusing anything. */
async function getOrFetchMarketEvidence(
  supabase: SupabaseClient<Database>,
  title: string,
  oneLiner: string,
  category: string,
): Promise<MarketEvidenceItem[]> {
  const cacheKey = `${category.toLowerCase().trim()}::${title.toLowerCase().trim()}`;

  const cached = await supabase
    .from("research_cache")
    .select("result, expires_at")
    .eq("cache_key", cacheKey)
    .maybeSingle();
  if (cached.data && new Date(cached.data.expires_at) > new Date()) {
    return cached.data.result as unknown as MarketEvidenceItem[];
  }

  const items = await researchMarketEvidence(title, oneLiner, category);

  await supabase.from("research_cache").upsert({
    cache_key: cacheKey,
    query: `${category} — ${title}`,
    result: items as unknown as Json,
    sources: items.map((i) => ({ title: i.sourceTitle, url: i.sourceUrl })) as unknown as Json[],
    expires_at: new Date(Date.now() + RESEARCH_CACHE_TTL_MS).toISOString(),
  });

  return items;
}

async function loadLatestBusinessDna(supabase: SupabaseClient<Database>, userId: string) {
  const { data, error } = await supabase
    .from("business_dna")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("No Business DNA found — complete the consultation first.");
  return data;
}

/** Persists one full opportunity package: the opportunities row (candidate
 * = the complete package, detail included), a mirrored opportunity_details
 * row (see profile.ts for why), and its complete pre-built roadmap. No
 * Gemini call happens in here — the package was already generated by the
 * caller. */
async function persistOpportunityPackage(
  supabase: SupabaseClient<Database>,
  userId: string,
  businessDnaId: string,
  profile: NormalizedProfile,
  pkg: OpportunityPackage,
  batchNumber: number,
  roadmapStatus: "active" | "available",
) {
  const score = computeFitScore(profile, pkg.fitSignals);

  const { data: oppRow, error: oppError } = await supabase
    .from("opportunities")
    .insert({
      user_id: userId,
      business_dna_id: businessDnaId,
      title: pkg.title,
      one_liner: pkg.plainEnglishSummary,
      who_for: pkg.customer,
      fit_score: score.total,
      score_breakdown: score as unknown as Json,
      candidate: pkg as unknown as Json,
      status: "active" as const,
      batch_number: batchNumber,
      ai_model: MODEL,
    })
    .select("*")
    .single();
  if (oppError || !oppRow) throw new Error(oppError?.message ?? "Failed to save opportunity");

  const { error: detailError } = await supabase.from("opportunity_details").insert({
    opportunity_id: oppRow.id,
    user_id: userId,
    detail: pkg as unknown as Json,
    ai_model: MODEL,
  });
  if (detailError) throw new Error(detailError.message);

  await createRoadmap(supabase, userId, oppRow.id, pkg.roadmap, roadmapStatus);

  return oppRow;
}

/** The one explicit, user-triggered Gemini call behind "Explore More
 * Opportunities" (never automatic — see item 3/64/66). Each newly
 * explored opportunity gets its full detail + roadmap up front, exactly
 * like the initial 3, so switching to one afterward is zero more calls.
 * None of them are made active automatically — the founder is already on
 * a path; exploring more doesn't silently switch it. */
export const exploreMoreOpportunities = createServerFn({ method: "POST" }).handler(async () => {
  const { supabase, user } = await requireUser();
  const dna = await loadLatestBusinessDna(supabase, user.id);
  const profile = dna.normalized_signals as unknown as NormalizedProfile;

  const { data: existing, error } = await supabase
    .from("opportunities")
    .select("title, status, dismiss_reason, batch_number")
    .eq("business_dna_id", dna.id);
  if (error) throw new Error(error.message);

  const excludeTitles = (existing ?? []).map((o) => o.title);
  const dismissedNotes = (existing ?? [])
    .filter((o) => o.status === "dismissed" && o.dismiss_reason)
    .map((o) => `"${o.title}" was dismissed because: ${o.dismiss_reason}`);
  const nextBatch = Math.max(1, ...(existing ?? []).map((o) => o.batch_number)) + 1;

  const batch = await generateOpportunityPackageBatch(profile, {
    excludeTitles,
    dismissedNotes,
    count: CANDIDATES_PER_BATCH,
  });

  const rows = [];
  for (const pkg of batch.opportunities) {
    rows.push(
      await persistOpportunityPackage(
        supabase,
        user.id,
        dna.id,
        profile,
        pkg,
        nextBatch,
        "available",
      ),
    );
  }
  return rows.sort((a, b) => b.fit_score - a.fit_score);
});

export const getOpportunities = createServerFn({ method: "GET" }).handler(async () => {
  const { supabase, user } = await requireUser();
  // Same deterministic tie-break as getDashboard — see its comment.
  const { data, error } = await supabase
    .from("opportunities")
    .select("*")
    .eq("user_id", user.id)
    .order("fit_score", { ascending: false })
    .order("created_at", { ascending: true });
  if (error) throw new Error(error.message);
  return data;
});

export const getOpportunity = createServerFn({ method: "GET" })
  .validator(z.object({ id: z.string().uuid() }))
  .handler(async ({ data }) => {
    const { supabase, user } = await requireUser();

    const { data: opportunity, error } = await supabase
      .from("opportunities")
      .select("*")
      .eq("id", data.id)
      .eq("user_id", user.id)
      .single();
    if (error || !opportunity) throw new Error(error?.message ?? "Opportunity not found");

    const dnaRow = await supabase
      .from("business_dna")
      .select("normalized_signals")
      .eq("id", opportunity.business_dna_id)
      .single();
    if (dnaRow.error || !dnaRow.data)
      throw new Error("Business DNA not found for this opportunity");
    const profile = dnaRow.data.normalized_signals as unknown as NormalizedProfile;

    // Every opportunity generated by the one-call architecture already has
    // its detail mirrored here at creation time (see profile.ts /
    // persistOpportunityPackage) — this lazy-generate branch only fires
    // for pre-migration rows that predate that change.
    let { data: detailRow } = await supabase
      .from("opportunity_details")
      .select("detail")
      .eq("opportunity_id", opportunity.id)
      .maybeSingle();

    if (!detailRow) {
      const detail = await generateOpportunityDetail(
        profile,
        opportunity.candidate as unknown as OpportunityCandidate,
      );
      const inserted = await supabase
        .from("opportunity_details")
        .insert({
          opportunity_id: opportunity.id,
          user_id: user.id,
          detail: detail as unknown as Json,
          ai_model: MODEL,
        })
        .select("detail")
        .single();
      if (inserted.error) throw new Error(inserted.error.message);
      detailRow = inserted.data;
    }

    // Market evidence is READ-ONLY here — no Gemini call on navigation.
    // Fetching/refreshing it is a separate, explicit action (see
    // refreshMarketEvidence below), matching every other page in the
    // workspace: viewing already-persisted data never costs an AI call.
    const { data: evidence } = await supabase
      .from("opportunity_evidence")
      .select("*")
      .eq("opportunity_id", opportunity.id);

    // Read-only, compact — powers the "Why You" founder<->business match
    // visualization with real stored signals instead of re-deriving
    // anything or fabricating a comparison.
    const founderSummary = {
      weeklyHours: profile.time.weeklyHours,
      capitalINR: profile.resources.capitalINR,
      skills: profile.skills.map((s) => s.name),
      riskAppetite: profile.risk.appetite,
    };

    return { opportunity, detail: detailRow.detail, evidence: evidence ?? [], founderSummary };
  });

/** The ONLY way opportunity_evidence ever gets a live Gemini call — an
 * explicit "Refresh Market Evidence" click, never navigation. Cached
 * globally per category+title for 30 days (see getOrFetchMarketEvidence),
 * so most calls of this across different founders are cache hits anyway. */
export const refreshMarketEvidence = createServerFn({ method: "POST" })
  .validator(z.object({ opportunityId: z.string().uuid() }))
  .handler(async ({ data }) => {
    const { supabase, user } = await requireUser();

    const { data: opportunity, error } = await supabase
      .from("opportunities")
      .select("id, title, one_liner, candidate")
      .eq("id", data.opportunityId)
      .eq("user_id", user.id)
      .single();
    if (error || !opportunity) throw new Error(error?.message ?? "Opportunity not found");

    const items = await getOrFetchMarketEvidence(
      supabase,
      opportunity.title,
      opportunity.one_liner,
      (opportunity.candidate as unknown as OpportunityCandidate).category,
    );

    // Replace rather than accumulate — a refresh should reflect the latest
    // research, not pile duplicate claims on top of stale ones.
    await supabase.from("opportunity_evidence").delete().eq("opportunity_id", opportunity.id);
    const rows = items.map((item) => ({
      opportunity_id: opportunity.id,
      user_id: user.id,
      claim: item.claim,
      label: item.label,
      source_title: item.sourceTitle,
      source_url: item.sourceUrl,
    }));
    const inserted = await supabase.from("opportunity_evidence").insert(rows).select("*");
    if (inserted.error) throw new Error(inserted.error.message);

    return { evidence: inserted.data };
  });

export const submitIdeaFeedback = createServerFn({ method: "POST" })
  .validator(
    z.object({
      opportunityId: z.string().uuid(),
      feedback: z.enum(["interested", "maybe_later", "not_for_me", "saved"]),
      reason: z.string().optional(),
    }),
  )
  .handler(async ({ data }) => {
    const { supabase, user } = await requireUser();

    const { error: feedbackError } = await supabase.from("idea_feedback").insert({
      user_id: user.id,
      opportunity_id: data.opportunityId,
      feedback: data.feedback,
      reason: data.reason ?? null,
    });
    if (feedbackError) throw new Error(feedbackError.message);

    if (data.feedback === "not_for_me" || data.feedback === "saved") {
      const { error: statusError } = await supabase
        .from("opportunities")
        .update({
          status: data.feedback === "not_for_me" ? "dismissed" : "saved",
          dismiss_reason: data.feedback === "not_for_me" ? (data.reason ?? null) : null,
        })
        .eq("id", data.opportunityId)
        .eq("user_id", user.id);
      if (statusError) throw new Error(statusError.message);
    }

    return { ok: true };
  });

/** Switching opportunities costs ZERO Gemini calls (item 37): every
 * candidate's roadmap was already fully built at generation time, so this
 * just flips database status — archive whichever roadmap was active
 * (preserving its progress/history), then reactivate the target
 * opportunity's own pre-built roadmap (recomputing only its remaining
 * tasks' deadlines relative to now — see activateRoadmap). */
export const switchSelectedOpportunity = createServerFn({ method: "POST" })
  .validator(z.object({ opportunityId: z.string().uuid() }))
  .handler(async ({ data }) => {
    const { supabase, user } = await requireUser();

    const { error: clearError } = await supabase
      .from("opportunities")
      .update({ status: "active" })
      .eq("user_id", user.id)
      .eq("status", "selected");
    if (clearError) throw new Error(clearError.message);

    await archiveActiveRoadmap(supabase, user.id);

    const { error: selectError } = await supabase
      .from("opportunities")
      .update({ status: "selected" })
      .eq("id", data.opportunityId)
      .eq("user_id", user.id);
    if (selectError) throw new Error(selectError.message);

    const { data: roadmap, error: roadmapError } = await supabase
      .from("roadmaps")
      .select("id")
      .eq("opportunity_id", data.opportunityId)
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (roadmapError) throw new Error(roadmapError.message);

    if (roadmap) {
      await activateRoadmap(supabase, user.id, roadmap.id);
    } else {
      // Pre-migration opportunity that never got a roadmap pre-built —
      // the only place left in the app that still needs a live Gemini
      // call for a roadmap, and only ever for this legacy case.
      const { data: opportunity, error: oppError } = await supabase
        .from("opportunities")
        .select("title, candidate, business_dna_id")
        .eq("id", data.opportunityId)
        .eq("user_id", user.id)
        .single();
      if (oppError || !opportunity) throw new Error(oppError?.message ?? "Opportunity not found");

      const dnaRow = await supabase
        .from("business_dna")
        .select("normalized_signals")
        .eq("id", opportunity.business_dna_id)
        .single();
      if (dnaRow.error || !dnaRow.data) throw new Error("Business DNA not found");
      const profile = dnaRow.data.normalized_signals as unknown as NormalizedProfile;
      const candidate = opportunity.candidate as unknown as OpportunityCandidate;

      const detail = await generateOpportunityDetail(profile, candidate);
      const plan = await generateRoadmapPlan(profile, opportunity.title, detail);
      await createRoadmap(supabase, user.id, data.opportunityId, plan, "active");
    }

    return { ok: true };
  });
