/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as FindMyBusinessIdeaRouteImport } from './routes/find-my-business-idea'
import { Route as ForOrganizationsRouteImport } from './routes/for-organizations'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReviewPublicRouteImport } from './routes/review-public'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard/roadmap'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOpportunitiesIdRouteImport } from './routes/dashboard/opportunities/$id'
import { Route as DashboardRoadmapBuildingRouteImport } from './routes/dashboard/roadmap/building'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyBusinessIdeaRoute = FindMyBusinessIdeaRouteImport.update({
  id: '/find-my-business-idea',
  path: '/find-my-business-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganizationsRoute = ForOrganizationsRouteImport.update({
  id: '/for-organizations',
  path: '/for-organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPublicRoute = ReviewPublicRouteImport.update({
  id: '/review-public',
  path: '/review-public',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/dashboard/roadmap',
  path: '/dashboard/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOpportunitiesIdRoute =
  DashboardOpportunitiesIdRouteImport.update({
    id: '/dashboard/opportunities/$id',
    path: '/dashboard/opportunities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoadmapBuildingRoute =
  DashboardRoadmapBuildingRouteImport.update({
    id: '/building',
    path: '/building',
    getParentRoute: () => DashboardRoadmapRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/data-deletion': typeof DataDeletionRoute
  '/find-my-business-idea': typeof FindMyBusinessIdeaRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/review-public': typeof ReviewPublicRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/opportunities/$id': typeof DashboardOpportunitiesIdRoute
  '/dashboard/roadmap/building': typeof DashboardRoadmapBuildingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/data-deletion': typeof DataDeletionRoute
  '/find-my-business-idea': typeof FindMyBusinessIdeaRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/review-public': typeof ReviewPublicRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/opportunities/$id': typeof DashboardOpportunitiesIdRoute
  '/dashboard/roadmap/building': typeof DashboardRoadmapBuildingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/data-deletion': typeof DataDeletionRoute
  '/find-my-business-idea': typeof FindMyBusinessIdeaRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/review-public': typeof ReviewPublicRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/opportunities/$id': typeof DashboardOpportunitiesIdRoute
  '/dashboard/roadmap/building': typeof DashboardRoadmapBuildingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/data-deletion'
    | '/find-my-business-idea'
    | '/for-organizations'
    | '/how-it-works'
    | '/privacy'
    | '/review'
    | '/review-public'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/opportunities/$id'
    | '/dashboard/roadmap/building'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/data-deletion'
    | '/find-my-business-idea'
    | '/for-organizations'
    | '/how-it-works'
    | '/privacy'
    | '/review'
    | '/review-public'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/opportunities/$id'
    | '/dashboard/roadmap/building'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/data-deletion'
    | '/find-my-business-idea'
    | '/for-organizations'
    | '/how-it-works'
    | '/privacy'
    | '/review'
    | '/review-public'
    | '/sign-in'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/opportunities/$id'
    | '/dashboard/roadmap/building'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  DataDeletionRoute: typeof DataDeletionRoute
  FindMyBusinessIdeaRoute: typeof FindMyBusinessIdeaRoute
  ForOrganizationsRoute: typeof ForOrganizationsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRoute
  ReviewPublicRoute: typeof ReviewPublicRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOpportunitiesIdRoute: typeof DashboardOpportunitiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-business-idea': {
      id: '/find-my-business-idea'
      path: '/find-my-business-idea'
      fullPath: '/find-my-business-idea'
      preLoaderRoute: typeof FindMyBusinessIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organizations': {
      id: '/for-organizations'
      path: '/for-organizations'
      fullPath: '/for-organizations'
      preLoaderRoute: typeof ForOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-public': {
      id: '/review-public'
      path: '/review-public'
      fullPath: '/review-public'
      preLoaderRoute: typeof ReviewPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/dashboard/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/opportunities/$id': {
      id: '/dashboard/opportunities/$id'
      path: '/dashboard/opportunities/$id'
      fullPath: '/dashboard/opportunities/$id'
      preLoaderRoute: typeof DashboardOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roadmap/building': {
      id: '/dashboard/roadmap/building'
      path: '/building'
      fullPath: '/dashboard/roadmap/building'
      preLoaderRoute: typeof DashboardRoadmapBuildingRouteImport
      parentRoute: typeof DashboardRoadmapRoute
    }
  }
}

interface DashboardRoadmapRouteChildren {
  DashboardRoadmapBuildingRoute: typeof DashboardRoadmapBuildingRoute
}

const DashboardRoadmapRouteChildren: DashboardRoadmapRouteChildren = {
  DashboardRoadmapBuildingRoute: DashboardRoadmapBuildingRoute,
}

const DashboardRoadmapRouteWithChildren =
  DashboardRoadmapRoute._addFileChildren(DashboardRoadmapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  DataDeletionRoute: DataDeletionRoute,
  FindMyBusinessIdeaRoute: FindMyBusinessIdeaRoute,
  ForOrganizationsRoute: ForOrganizationsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRoute,
  ReviewPublicRoute: ReviewPublicRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardRoadmapRoute: DashboardRoadmapRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOpportunitiesIdRoute: DashboardOpportunitiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
